### ISSUE TITLE
move parallelMap package from "Suggests" to "Imports" in DESCRIPTION file

### ISSUE THREAD

**Issue by TommyJones** [JonasRieger/ldaPrototype#3]
{parallelMap} is called when running `LDARep`, a core function of the package. But because it is in "Suggests" it isn't installed by default on package install. So, if someone calls `install.packages("ldaPrototype")` and doesn't have {parallelMap} already installed, running `LDARep` or a function that calls it will result in an error.

> `Error in loadNamespace(name) : there is no package called ‘parallelMap’`

I'd recommend moving parallelMap to Imports. 

FWIW, this shouldn't impact the JOSS review IMO. But it would make the package more useful. (My first call to `LDAPrototype` resulted in the above error.)

**Comment by JonasRieger** [comment]
I've thought about that, too. Since it is one of the main features of the package to do the calculations in parallel (or via batchtools), these packages should probably be included in the imports. The idea not to do this was because I wanted to keep the imports to a minimum and these packages are not essential.
But I also noticed that it is a bit annoying to have to install these two packages every time myself.
Maybe future should go into the imports as well - this package determines the number of available cores if the number is not given by the user.

**Comment by JonasRieger** [comment]
Fixed it https://github.com/JonasRieger/ldaPrototype/commit/7838aebe2584bf5ed46125363964cf69a6f70c98
