### ISSUE TITLE
Error: (unknown) (@test_jaccardTopics.R#8):   wrong sign in 'by' argument

### ISSUE THREAD

**Issue by HenrikBengtsson** [JonasRieger/ldaPrototype#8]
Hi.  When running revdep checks, **ldaPrototype** has produced the below error.  I haven't looked at the code, so I don't know what `N` is but it looks like `N-2` < `x` and that's unexpected.  Maybe you're able to see how this could happen.

```r
...
  The following object is masked from 'package:stats':
  
      cutree
  
  > 
  > test_check("ldaPrototype")
  ── 1. Error: (unknown) (@test_jaccardTopics.R#8)  ──────────────────────────────
  wrong sign in 'by' argument
  Backtrace:
   1. ldaPrototype::jaccardTopics(mtopics, pm.backend = "socket")
   2. ldaPrototype:::jaccardTopics.parallel(...)
   3. base::lapply(...)
   4. ldaPrototype:::FUN(X[[i]], ...)
   6. base::seq.default(x, N - 2, max(ncpus, 2))
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 243 | SKIPPED: 0 | WARNINGS: 2 | FAILED: 1 ]
  1. Error: (unknown) (@test_jaccardTopics.R#8) 
  
  Error: testthat unit tests failed
  Execution halted
```

**Comment by JonasRieger** [comment]
First of all I would like to apologize for the really late answer. Unfortunately I didn't get a message about the new issues of this package, because the setting was not right.

Regarding the problem: Interestingly, the bug has never been noticed until now, because the code has only run on systems with a maximum of 18 cores (N = 20 in this case). Anyway, I fixed the bug and a new version will be released soon on CRAN. 

Thanks for the note!
