### ISSUE TITLE
Failure with dev testthat

### ISSUE THREAD

**Issue by hadley** [JonasRieger/ldaPrototype#9]
I see:

```
> test_check("ldaPrototype")
── Warning (test_LDABatch.R:146:3): is.LDABatch ────────────────────────────────
Parameter(s) num.iterations are duplicated. Take last one(s).

Killed
```

Can you please take a look? I'm planning to submit testthat to CRAN in about a month.

**Comment by JonasRieger** [comment]
First of all I would like to apologize for the really late answer. Unfortunately I didn't get a message about the new issues of this package, because the setting was not right.

About the problem: In fact I tested with `expect_error` in two places. But at both places a warning preceded the error, so that after the new release of testthat a warning was thrown. I fixed the bug and a new version will be released soon on CRAN.

Thanks for the comment!
